name: Build
on:
  workflow_dispatch:  # 手動実行を可能にする
  push:
    branches:
      - main  # mainブランチへのプッシュ時
    paths:
      - 'src/**'  # srcディレクトリ配下の変更時
      - 'plugin.json'  # plugin.jsonの変更時
      - '.github/workflows/**'  # ワークフロー自体の変更時
  release:
    types: created  # リリース作成時

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x  # 複数のバージョンをインストール（互換性のため）

      - name: Read version
        run: |
          $json = Get-Content -path .\plugin.json -Raw | ConvertFrom-Json
          echo "PLUGIN_VERSION=$($json.Version)" >> $env:GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          dotnet build --configuration Release --no-restore

      - name: Package
        run: |
          dotnet pack -p:Platform=x64 --no-build --configuration Release
          dotnet pack -p:Platform=ARM64 --no-build --configuration Release

      # リリース時のみアップロードを実行
      - name: Upload x64 To Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: bin/Translator_x64.zip
          asset_name: Translator-${{env.PLUGIN_VERSION}}-x64.zip

      - name: Upload ARM64 To Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file: bin/Translator_ARM64.zip
          asset_name: Translator-${{env.PLUGIN_VERSION}}-arm64.zip

      # プッシュ時のみアーティファクトとして保存
      - name: Upload Build Artifacts
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: PowerTranslator-${{env.PLUGIN_VERSION}}
          path: |
            bin/Translator_x64.zip
            bin/Translator_ARM64.zip
          retention-days: 5  # アーティファクトの保持期間を5日間に設定
